services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - app-vue

networks:
  app-vue:
    driver: bridge